#!/usr/bin/env bash
# TASK-125（対象ビヘイビア: CORE-1。ポインタ: docs/spec/05-tasks.md TASK-125）の
# コア API シグネチャ差分検知チェック。
#
# `crates/engine/src/core.rs` の `pub trait VectorCore` と `crates/engine/src/kernel.rs`
# の `pub trait SearchProvider` の定義ブロックを正規化抽出し、コミット済みの
# ゴールデンファイル（crates/engine/api/core_api.snapshot）と比較する。差分があれば
# プロトコル層（wire-server 等）に影響しうるコア API 変更が意図せず紛れ込んだ可能性が
# あるとみなし、非 0 終了する（Makefile の core-api-check ターゲット・CI の
# core-api-check ジョブから呼ばれる。cargo を使わない軽量テキストチェックのため
# rust-ci ジョブとは独立に実行できる）。
#
# 正当な API 変更時は本スクリプトを --update 付きで再実行してスナップショットを
# 再生成し、その差分を明示的なコミットとしてレビューへ残す運用とする
# （変更を禁止するチェックではなく、変わったことを可視化するチェック）。
#
# 使い方: scripts/check_core_api.sh [--update]

set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SNAPSHOT="${REPO_ROOT}/crates/engine/api/core_api.snapshot"

MODE="check"
if [ "${1:-}" = "--update" ]; then
  MODE="update"
elif [ "${1:-}" != "" ]; then
  echo "ERROR: unknown argument: ${1}" >&2
  echo "usage: $(basename "$0") [--update]" >&2
  exit 1
fi

# `file:trait_name` の対を 1 件抽出する。抽出規則: `^pub trait <trait_name>` 行から
# 対応する `^}` 行までを 1 ブロックとして取り出し、`///`・`//` コメント行と空行を除去、
# 行末空白を正規化する（インデントは保持し、実質的なシグネチャ差分だけを比較対象にする）。
# 対象ブロックが 1 件も見つからない場合は fail-closed でエラー終了する（trait 名の
# 変更・ファイル移動でチェックが空振り green になることを防ぐ）。
extract_trait_block() {
  local file="$1"
  local trait_name="$2"

  if [ ! -f "${file}" ]; then
    echo "ERROR: source file not found: ${file}" >&2
    return 1
  fi

  local block
  block="$(awk -v trait="pub trait ${trait_name}" '
    $0 ~ ("^" trait) { found = 1 }
    found { print }
    found && /^}/ { exit }
  ' "${file}")"

  if [ -z "${block}" ]; then
    echo "ERROR: trait block not found: ${trait_name} in ${file}" >&2
    return 1
  fi
  # 抽出末尾が `^}` で終わっていない場合（ファイル末尾まで到達して抜けた等）も、
  # 閉じ括弧を検出できなかった不完全な抽出として fail-closed にする。
  local last_line
  last_line="$(printf '%s\n' "${block}" | tail -n 1)"
  if [ "${last_line}" != "}" ]; then
    echo "ERROR: trait block for ${trait_name} in ${file} has no closing brace (extraction incomplete)" >&2
    return 1
  fi

  printf '%s\n' "${block}" | sed -e '/^[[:space:]]*\/\/\//d' -e '/^[[:space:]]*\/\//d' -e '/^[[:space:]]*$/d' -e 's/[[:space:]]*$//'
}

VECTOR_CORE_FILE="${REPO_ROOT}/crates/engine/src/core.rs"
SEARCH_PROVIDER_FILE="${REPO_ROOT}/crates/engine/src/kernel.rs"

VECTOR_CORE_BLOCK="$(extract_trait_block "${VECTOR_CORE_FILE}" "VectorCore")" || exit 1
SEARCH_PROVIDER_BLOCK="$(extract_trait_block "${SEARCH_PROVIDER_FILE}" "SearchProvider")" || exit 1

GENERATED="$(
  {
    echo "# generated by scripts/check_core_api.sh --update (TASK-125). Do not hand-edit."
    echo "# source: crates/engine/src/core.rs :: VectorCore"
    printf '%s\n' "${VECTOR_CORE_BLOCK}"
    echo
    echo "# source: crates/engine/src/kernel.rs :: SearchProvider"
    printf '%s\n' "${SEARCH_PROVIDER_BLOCK}"
  }
)"

if [ "${MODE}" = "update" ]; then
  mkdir -p "$(dirname "${SNAPSHOT}")"
  printf '%s\n' "${GENERATED}" >"${SNAPSHOT}"
  echo "updated: ${SNAPSHOT}"
  exit 0
fi

if [ ! -f "${SNAPSHOT}" ]; then
  echo "ERROR: snapshot not found: ${SNAPSHOT}" >&2
  echo "run: scripts/check_core_api.sh --update" >&2
  exit 1
fi

if ! diff -u "${SNAPSHOT}" <(printf '%s\n' "${GENERATED}"); then
  echo "" >&2
  echo "ERROR: core API signature changed; if intentional, run scripts/check_core_api.sh --update and commit the snapshot" >&2
  exit 1
fi

echo "ok: core API signature matches ${SNAPSHOT}"
